name: Deploy landing page to Pages

on:
  push:
    branches: ["master", "main"]
    tags: ["v*"]
  # Permet de lancer manuellement depuis l'onglet Actions
  workflow_dispatch:

# Permissions nécessaires pour GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permet d'annuler les déploiements obsolètes
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Inject Dynamic Version for SEO
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          VERSION=${LATEST_TAG#v}
          echo "Dernière version trouvée : $VERSION. Injection dans le JSON-LD Schema..."
          sed -i "s/\"softwareVersion\": \"[^\"]*\"/\"softwareVersion\": \"$VERSION\"/g" website/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Point vital : on choisit le dossier "website"
          path: './website'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
